repos:
  # Ruff for linting and formatting
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.259
    hooks:
      - id: ruff
        args: ['--fix']  # Automatically fix issues

  # Mypy for type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy
        args: ['--ignore-missing-imports', --show-error-codes]  # Adjust this based on your project needs
        additional_dependencies: ['types-requests', 'types-PyYAML']

  # Basic pre-commit hooks for common checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace  # Remove trailing whitespace
      - id: end-of-file-fixer  # Ensure files end with a newline
      - id: check-yaml  # Validate YAML files
      - id: check-merge-conflict  # Prevent committing unresolved merge conflicts
      - id: detect-private-key  # Detect private keys to prevent committing sensitive data
