[tool.poetry]
name = "ad-progression-pipeline"
version = "0.1.0"
description = ""
authors = ["Minh <tminh.us@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
imbalanced-learn = "0.1.1"
tensorflow = "2.17.0"
matplotlib = "^3.9.2"
numpy = "1.26.0"
pandas = "^2.2.2"
scikit-learn = "^1.5.1"
optuna = "^3.6.1"
pre-commit = "^3.8.0"
ruff = "^0.6.3"
mypy = "^1.11.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 150
